parameters:
  # wechat config
    wechat_Token: adp_wechat_samesame
    wechat_AppID: wx4868f82730292835
    wechat_AppSecret: b994d3233e85e53712189f21880b83e3

    wechat_api_permission:
      wechat_api_wechatmenu: change wechat menu
