wechat_api_homepage:
    path:     /hello/{name}
    defaults: { _controller: WechatApiBundle:Default:index }

wechat_api_feedback:
    path:     /wechat
    defaults: { _controller: WechatApiBundle:Default:wechat }

wechat_api_api1:
    path:     /api1
    defaults: { _controller: WechatApiBundle:Default:api1 }
