wechat_api_homepage:
    path:     /hello/{name}
    defaults: { _controller: WechatApiBundle:Default:index }

wechat_api_feedback:
    path:     /wechat
    defaults: { _controller: WechatApiBundle:Default:wechat }

wechat_api_api1:
    path:     /api1
    defaults: { _controller: WechatApiBundle:Default:api1 }

# wechat_wechatmenu start
wechat_wechatmenu_getmenus:
    path:     /wechatmenu/getmenus
    defaults: { _controller: WechatApiBundle:Wechatmenu:getmenus }

wechat_wechatmenu_getmmenu:
    path:     /wechatmenu/getmmenu
    defaults: { _controller: WechatApiBundle:Wechatmenu:getmmenu }

wechat_wechatmenu_createmenu:
    path:     /wechatmenu/createmenu
    defaults: { _controller: WechatApiBundle:Wechatmenu:createmenu }

wechat_wechatmenu_getbuttoninfo:
    path:     /wechatmenu/getbuttoninfo
    defaults: { _controller: WechatApiBundle:Wechatmenu:getbuttoninfo }

wechat_wechatmenu_deletebutton:
    path:     /wechatmenu/deletebutton
    defaults: { _controller: WechatApiBundle:Wechatmenu:deletebutton }

wechat_wechatmenu_addsubbutton:
    path:     /wechatmenu/addsubbutton
    defaults: { _controller: WechatApiBundle:Wechatmenu:addsubbutton }

wechat_wechatmenu_addmbutton:
    path:     /wechatmenu/addmbutton
    defaults: { _controller: WechatApiBundle:Wechatmenu:addmbutton }

wechat_wechatmenu_updatebutton:
    path:     /wechatmenu/updatebutton
    defaults: { _controller: WechatApiBundle:Wechatmenu:updatebutton }

wechat_wechatmenu_updateevent:
    path:     /wechatmenu/updateevent
    defaults: { _controller: WechatApiBundle:Wechatmenu:updateevent }

wechat_wechatmenu_getevent:
    path:     /wechatmenu/getevent
    defaults: { _controller: WechatApiBundle:Wechatmenu:getevent }
# wechat_wechatmenu end

# wechat keyword start
wechat_keyword_keywordadd:
    path:     /wechat/keywordadd
    defaults: { _controller: WechatApiBundle:Keyword:keywordadd }

wechat_keyword_getkeywordlist:
    path:     /wechat/getkeywordlist
    defaults: { _controller: WechatApiBundle:Keyword:getkeywordlist }

wechat_keyword_keyworddel:
    path:     /wechat/keyworddel
    defaults: { _controller: WechatApiBundle:Keyword:keyworddel }

wechat_keyword_getkeywordinfo:
    path:     /wechat/getkeywordinfo
    defaults: { _controller: WechatApiBundle:Keyword:getkeywordinfo }

wechat_keyword_keywordupdate:
    path:     /wechat/keywordupdate
    defaults: { _controller: WechatApiBundle:Keyword:keywordupdate }
# wechat keyword end

# wechat autoreplay start
wechat_autoreply_autoreply:
    path:     /wechat/autoreply
    defaults: { _controller: WechatApiBundle:Autoreply:autoreply }

wechat_autoreply_autoreplyinfo:
    path:     /wechat/autoreplyinfo
    defaults: { _controller: WechatApiBundle:Autoreply:autoreplyinfo }

wechat_autoreply_autoreplydel:
    path:     /wechat/autoreplydel
    defaults: { _controller: WechatApiBundle:Autoreply:autoreplydel }
# wechat autoreplay end

# wechat page list start
wechat_page_menu:
    path:     /wechat/menu
    defaults: { _controller: WechatApiBundle:Page:menu }

wechat_page_keyword:
    path:     /wechat/keyword
    defaults: { _controller: WechatApiBundle:Page:menu }
# wechat page list end
