wechat_api_homepage:
    path:     /hello/{name}
    defaults: { _controller: WechatApiBundle:Default:index }

wechat_api_feedback:
    path:     /wechat
    defaults: { _controller: WechatApiBundle:Default:wechat }

wechat_api_api1:
    path:     /api1
    defaults: { _controller: WechatApiBundle:Default:api1 }

# wechat_wechatmenu start
wechat_wechatmenu_getmenus:
    path:     /wechatmenu/getmenus
    defaults: { _controller: WechatApiBundle:Wechatmenu:getmenus }

wechat_wechatmenu_getmmenu:
    path:     /wechatmenu/getmmenu
    defaults: { _controller: WechatApiBundle:Wechatmenu:getmmenu }

wechat_wechatmenu_createmenu:
    path:     /wechatmenu/createmenu
    defaults: { _controller: WechatApiBundle:Wechatmenu:createmenu }

wechat_wechatmenu_getbuttoninfo:
    path:     /wechatmenu/getbuttoninfo
    defaults: { _controller: WechatApiBundle:Wechatmenu:getbuttoninfo }

wechat_wechatmenu_deletebutton:
    path:     /wechatmenu/deletebutton
    defaults: { _controller: WechatApiBundle:Wechatmenu:deletebutton }

wechat_wechatmenu_addsubbutton:
    path:     /wechatmenu/addsubbutton
    defaults: { _controller: WechatApiBundle:Wechatmenu:addsubbutton }

wechat_wechatmenu_addmbutton:
    path:     /wechatmenu/addmbutton
    defaults: { _controller: WechatApiBundle:Wechatmenu:addmbutton }

wechat_wechatmenu_updatebutton:
    path:     /wechatmenu/updatebutton
    defaults: { _controller: WechatApiBundle:Wechatmenu:updatebutton }

wechat_wechatmenu_updateevent:
    path:     /wechatmenu/updateevent
    defaults: { _controller: WechatApiBundle:Wechatmenu:updateevent }

wechat_wechatmenu_getevent:
    path:     /wechatmenu/getevent
    defaults: { _controller: WechatApiBundle:Wechatmenu:getevent }
# wechat_wechatmenu end

wechat_page_getevent:
    path:     /page/menu
    defaults: { _controller: WechatApiBundle:Page:menu }
