services:
#    wechat_api.example:
#        class: Wechat\ApiBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
        my.Wechat:
          class: Wechat\ApiBundle\Modals\classes\Wechat
          arguments: [@service_container]
