parameters:
  # wechat config
    article_permission:
      article_control: article control

    article_pages:
      article_page_page:
        goto: user_page_login
        permission: article_control

    article_papis:
      article_api_papi_articleadd:
        goto: user_out_notpassede
        permission: article_control

      article_api_papi_editarticle:
        goto: user_out_notpassede
        permission: article_control

      article_api_papi_deletearticle:
        goto: user_out_notpassede
        permission: article_control
